#!/bin/bash
# guide-kit-sync.sh — vendor a tagged release of iwesys/guide-kit into the
# template tree (guide-kit/), so generate-manifest.sh picks it up and update.sh
# delivers it to users' template clones ($IWE_TEMPLATE/guide-kit/).
#
# Author-only tooling: excluded from user delivery via EXCLUDED_SCRIPTS in
# generate-manifest.sh. Decision record: WP-483 Ф4, peer-session
# 2026-07-16-03-wp483-f4-archgate-sync (DRR lives in the author's governance repo).
#
# Contract:
#   * the copy is the WHOLE tag tree minus .git/.github — including tests and
#     .gitignore (the nested .gitignore keeps a user's live guide-kit.config.yaml,
#     which may hold an LLM API key, out of update.sh's `git add -A` commit);
#   * provenance lives OUTSIDE the copy (scripts/guide-kit-sync-state.yaml), so
#     the copy stays byte-identical to the source tag — the drift check in
#     validate-template.yml relies on exactly this;
#   * order matters: rsync → git add → generate-manifest.sh — the manifest reads
#     `git ls-files`, unstaged files silently drop out of delivery;
#   * sync from a release tag only, cloned fresh — never from a working clone,
#     so uncommitted local state cannot be smuggled into the template.
#
# Usage: bash scripts/guide-kit-sync.sh [--tag vX.Y.Z] [--source-repo URL] [--dry-run]
#   --tag          release tag to sync (default: highest version tag on the remote)
#   --source-repo  source repository (default: https://github.com/iwesys/guide-kit.git)
#   --dry-run      show what would change, write nothing

set -euo pipefail

FMT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_REPO="https://github.com/iwesys/guide-kit.git"
TAG=""
DRY_RUN=false

usage() {
    grep '^# Usage' -A 3 "$0" | sed 's/^# \{0,1\}//'
}

# Strict parsing: an unknown flag is an error, not a silently ignored no-op
# (a swallowed typo like --dryrun once triggered a live production run —
# WP-483 Ф1.5 incident, 2026-07-15).
while [ $# -gt 0 ]; do
    case "$1" in
        --tag)         TAG="${2:?--tag requires a value}"; shift 2 ;;
        --source-repo) SOURCE_REPO="${2:?--source-repo requires a value}"; shift 2 ;;
        --dry-run)     DRY_RUN=true; shift ;;
        *) echo "ERROR: unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

# Default tag = highest STABLE version tag on the remote (vX.Y.Z only —
# without the filter `sort -V` ranks v0.2.0-rc1 above v0.2.0 and a pre-release
# would silently become the vendored copy). Refuse to sync untagged state:
# the whole model pins the copy to a released tag.
if [ -z "$TAG" ]; then
    TAG=$(git ls-remote --tags --refs "$SOURCE_REPO" | awk -F/ '{print $NF}' \
        | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)
    if [ -z "$TAG" ]; then
        echo "ERROR: no stable release tags (vX.Y.Z) found on $SOURCE_REPO — create one first (e.g. v0.1.0)." >&2
        exit 1
    fi
fi

TMP_CLONE=$(mktemp -d)
trap 'rm -rf "$TMP_CLONE"' EXIT

echo "Cloning $SOURCE_REPO at tag $TAG ..."
git clone --quiet --depth 1 --branch "$TAG" "$SOURCE_REPO" "$TMP_CLONE"
COMMIT_SHA=$(git -C "$TMP_CLONE" rev-parse HEAD)

# Anchored excludes: only the TOP-LEVEL .git/.github of the source are cut.
# A nested .github anywhere deeper (e.g. a test fixture) stays in the copy —
# the CI drift check removes only top-level dirs from its reference clone,
# so unanchored excludes here would make the diff permanently red.
RSYNC_FLAGS=(-a --delete --exclude=/.git --exclude=/.github)

if $DRY_RUN; then
    echo "Dry run — changes that a real run would apply to guide-kit/:"
    rsync -n -i "${RSYNC_FLAGS[@]}" "$TMP_CLONE/" "$FMT_ROOT/guide-kit/"
    echo "Dry run: nothing written, nothing staged."
    exit 0
fi

mkdir -p "$FMT_ROOT/guide-kit"
RSYNC_OUT=$(rsync -i "${RSYNC_FLAGS[@]}" "$TMP_CLONE/" "$FMT_ROOT/guide-kit/")

# Files removed by the new tag vanish from the manifest's `files`, but users
# only lose already-delivered files via deprecated_files in update-manifest.json
# (manual list) — without an entry their copies diverge from the tag forever.
# sed keeps the whole remainder of the line — awk '{print $2}' would truncate
# filenames containing spaces.
DELETED_FILES=$(printf '%s\n' "$RSYNC_OUT" | sed -n 's/^\*deleting[[:space:]]*//p' || true)
if [ -n "$DELETED_FILES" ]; then
    echo "WARNING: this tag removed files that were present in the previous copy:"
    printf '%s\n' "$DELETED_FILES" | sed 's|^|  guide-kit/|'
    echo "  Add each of them to deprecated_files in update-manifest.json,"
    echo "  otherwise already-delivered user copies keep the stale files forever."
fi

STATE_FILE="$FMT_ROOT/scripts/guide-kit-sync-state.yaml"
cat > "$STATE_FILE" <<EOF
# AUTO-GENERATED by scripts/guide-kit-sync.sh — do not edit by hand.
# Provenance of the vendored guide-kit/ copy. Kept OUTSIDE the copy so the
# copy stays byte-identical to the source tag (drift check contract).
# The copy itself is derived-only: never edit guide-kit/ in place — change
# the source repo, release a tag, re-run the sync.
source_repo: $SOURCE_REPO
tag: $TAG
commit: $COMMIT_SHA
synced_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

git -C "$FMT_ROOT" add guide-kit scripts/guide-kit-sync-state.yaml

echo "Synced guide-kit@$TAG ($COMMIT_SHA) into guide-kit/ and staged it."
echo "Next steps (one release commit):"
echo "  1. Add a CHANGELOG.md entry with a new version — the manifest takes its version from it."
echo "  2. If the sync reported removed files above — add them to deprecated_files in update-manifest.json."
echo "  3. bash generate-manifest.sh"
echo "  4. Review git status, commit guide-kit/ + update-manifest.json + CHANGELOG.md + state file, push."
